### ISSUE TITLE
ERROR at rosdep install --from-paths src -i -y --rosdistro $ROS_DISTRO during Installation

### ISSUE THREAD

**Issue by softgearko** [jr-robotics/robo-gym-robot-servers#12]
Hello.
I'm installing according to Ubuntu 20.04 - ROS Noetic - Python [>3.7] in Installation. I faced ERROR message at  rosdep install.

```
username@sg-vm-u20:~/robogym_ws$ rosdep install --from-paths src -i -y --rosdistro $ROS_DISTRO
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
panda_gazebo: Cannot locate rosdep definition for [franka_panda_description]
username@sg-vm-u20:~/robogym_ws$ 
```

Could you help me?

**Comment by Adarsh3559** [comment]
Try to download from here the drivers it might work. it worked for me from this link.

https://github.com/UniversalRobots/Universal_Robots_ROS_Driver

**Comment by softgearko** [comment]
I missed 
`git clone https://github.com/jr-robotics/franka_panda_description`
'rosdep install' works.
I'm sorry.
