### ISSUE TITLE
How can we implement other robots? 

### ISSUE THREAD

**Issue by letusfly85** [jr-robotics/robo-gym-robot-servers#2]
Hi, if we want to use other robots, for example, `sawyer`, how can we implement?
Are there any guidelines to implement?

**Comment by matteolucchi** [comment]
Hi, thank you for your interest in robo-gym! We have planned to provide more detailed documentation on how to integrate new robots but unfortunately we haven't had time to work on that yet, nevertheless I'll try to support you as best as I can. 

The first thing to do to implement a new robot is to make sure to have a simulation of the robot, in the case of the sawyer robot this should be publicly available. 

Once the simulation is setup you would move on to implementing a Robot Server ROS Package for the robot. I suggest you take as a reference the [UR Robot Server](https://github.com/jr-robotics/robo-gym-robot-servers/tree/master/ur_robot_server). The core of the robot server is in [robot_server.py](https://github.com/jr-robotics/robo-gym-robot-servers/blob/master/ur_robot_server/scripts/robot_server.py) which implements the grpc interface and in  [ros_bridge.py](https://github.com/jr-robotics/robo-gym-robot-servers/blob/master/ur_robot_server/scripts/ros_bridge.py) which implements the ROS interface to the real and simulated robot. 

If you want to have any more details or support I would be happy to give you more information or arrange a call to support you with that.

Matteo

**Comment by matteolucchi** [comment]
Hi, 

we just released a [basic example of a Robot Server implementation](https://github.com/jr-robotics/robo-gym-robot-servers/tree/master/example_robot_server) together with a [basic example of Environment](https://github.com/jr-robotics/robo-gym/blob/master/robo_gym/envs/example/example_env.py).

This should help to get started with implementing the Robot Server and and the Environment for  other robots. 

Cheers,
Matteo

**Comment by letusfly85** [comment]
@matteolucchi 

Hi, thank you for the great example!
We will check it 👍🏻 

Thank you!
