### ISSUE TITLE
Debug method for implementing other robots

### ISSUE THREAD

**Issue by mphamhung** [jr-robotics/robo-gym-robot-servers#4]
Hello, I'm trying to implement a turtlebot server, but I'm at a lost at how to debug. 

For example, I get an Rpc Error in the Server Manager when I try to initialize the environment, after suppressing the try-except block (sorry I'm having issues copying the text):

![image](https://user-images.githubusercontent.com/11167157/116918957-9690cb00-ac1e-11eb-986e-d4fa05c986d9.png)

Launching the Mir100 environment, I have no issue, so I'm not sure what fixes to attempt.

Any advice would be appreciated.

Thanks!

**Comment by mphamhung** [comment]
Moving my package into the robogym_ws got it working!

**Comment by matteolucchi** [comment]
Hi, I am happy to see that you got it working. I will close this one :)
