### ISSUE TITLE
Support for ROS2 ?

### ISSUE THREAD

**Issue by yassirnajmaoui** [jr-robotics/robo-gym-robot-servers#8]
Hi
I am wondering what is the current point of view of this project regarding ROS rolling.
Is it already supported?
Is it planned in the future?

**Comment by matteolucchi** [comment]
Hi @yassirnajmaoui !
We are currently not supporting ROS2 and also not planning to do so in the near future, some of the packages/drivers that we use have not been released yet and that is currently a blocker for us. Once these will become available we will consider moving to ROS2. 

Is there some specific reason why you would like to have ROS2 supported?

**Comment by yassirnajmaoui** [comment]
Thank you for your answer @matteolucchi 
I was looking for a gym environment involving UR robot arms. The best I could find was yours, but I am restricted to ROS2.
Thank you still for your contribution!
